title = "network device config"

[extend]
useDefault = true

[[rules]]
id = "crypt-password-hash"
description = "Detected a password hash"
regex = '''\$(?:[a-zA-Z0-9]+)\$([^\s:]+)'''

[[rules]]
id = "f5-password-unhashed"
description = "Detected an unhashed F5 password"
regex = '''encrypted-password\s+([^\$][^\s]+)'''

[[rules]]
id = "f5-master-key-unhashed"
description = "Detected an F5 unhashed master key"
regex = '''master-key\s+([^\$][^\s]+)'''

[[rules]]
id = "f5-ntp-key"
description = "Detected an F5 NTP key"
regex = '''(?ms)sys ntp {[^}]+?key \d+ ([^\s]+)'''

[[rules]]
id = "cisco-ntp-key"
description = "Detected a Cisco NTP key"
regex = '''ntp authentication-key \d+ \w+ ([^\s]+)'''

[[rules]]
id = "cisco-radius-server"
description = "Detected a Cisco RADIUS key"
regex = '''radius-server key \d+ ([^\s]+)'''

[[rules]]
id = "cisco-radius-key"
description = "Detected a Cisco RADIUS key"
regex = '''(?ms)radius[- ]?server(?:[^\n!]*\n\s+[^\n!]*)*?\s+key (?:\d+ )?([^\s]+)'''

[[rules]]
id = "cisco-ospf-message-digest-key"
description = "Detected a Cisco OSPF message digest key"
regex = '''ospf message-digest-key \d+ \w+ \d+ ([^\s]+)'''

[[rules]]
id = "cisco-failover-key"
description = "Detected a Cisco Failover Key"
regex = '''failover key ([^\s]+)'''

[[rules]]
id = "cisco-crypto-key"
description = "Detected a Cisco Crypto Key"
regex = '''crypto \w+ key ([^\s]+)'''

[[rules]]
id = "fortinet-password"
description = "Detected a Fortinet password"
regex = ''' ENC ([^\s]+)'''

[[rules]]
id = "cisco-neighbor-password"
description = "Detected a Cisco neighbor password"
regex = '''neighbor \S+ password (?:\d+ )?([^\s]+)'''

[[rules]]
id = "cisco-standby-auth"
description = "Detected a Cisco standby HSRP authentication key"
regex = '''standby \d+ authentication (?:md5 key-string|text)?\s*(?:\d+\s+)?([^\s]+)'''

[[rules]]
id = "cisco-key-chain-key"
description = "Detected a Cisco key chain key"
regex = '''key-string (?:\d+ )?([^\s]+)'''

[[rules]]
id = "cisco-snmp-community"
description = "Detected a Cisco SNMP community string"
regex = '''snmp-server community\s+([^\s]+)'''

[[rules]]
id = "generic-snmp-community"
description = "Detected a generic SNMP community string"
regex = '''(?m)^\s*community(?:-name)?\s+([^\s]+)'''

[[rules]]
id = "fortinet-snmp-community"
description = "Detected a Fortinet SNMP community string"
regex = '''(?ms)config system snmp community.+?set name "([^"]+)"'''
